/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumCard: typeof import('./components/music/AlbumCard.vue')['default']
    AlbumCardGrid: typeof import('./components/music/AlbumCardGrid.vue')['default']
    AlbumCarousel: typeof import('./components/music/AlbumCarousel.vue')['default']
    AlbumPreviewCard: typeof import('./components/music/AlbumPreviewCard.vue')['default']
    AppCarousel: typeof import('./components/app/AppCarousel.vue')['default']
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppNavigation: typeof import('./components/app/AppNavigation.vue')['default']
    AppTopPlayer: typeof import('./components/app/AppTopPlayer.vue')['default']
    AppWelcome: typeof import('./components/app/AppWelcome.vue')['default']
    AutoMarquee: typeof import('./components/common/auto-marquee.vue')['default']
    CloudItem: typeof import('./components/cloud/CloudItem.vue')['default']
    CreateAccount: typeof import('./components/account/CreateAccount.vue')['default']
    DropBreadcrumb: typeof import('./components/cloud/DropBreadcrumb.vue')['default']
    Expansion: typeof import('./components/common/expansion.vue')['default']
    FileSystem: typeof import('./components/cloud/FileSystem.vue')['default']
    FolderBreadcrumb: typeof import('./components/cloud/folder-breadcrumb.vue')['default']
    PathBreadcrumbs: typeof import('./components/cloud/PathBreadcrumbs.vue')['default']
    ResetPassword: typeof import('./components/account/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./components/common/section-title.vue')['default']
    SignIn: typeof import('./components/account/SignIn.vue')['default']
    SongCarousel: typeof import('./components/music/SongCarousel.vue')['default']
    SongList: typeof import('./components/music/SongList.vue')['default']
    TextareaForm: typeof import('./components/post/TextareaForm.vue')['default']
    WelcomeOM: typeof import('./components/WelcomeOM.vue')['default']
  }
}
