/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/password': RouteRecordInfo<'/account/password', '/account/password', Record<never, never>, Record<never, never>>,
    '/account/sign-in': RouteRecordInfo<'/account/sign-in', '/account/sign-in', Record<never, never>, Record<never, never>>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/app/cloud': RouteRecordInfo<'/app/cloud', '/app/cloud', Record<never, never>, Record<never, never>>,
    '/app/discovery': RouteRecordInfo<'/app/discovery', '/app/discovery', Record<never, never>, Record<never, never>>,
    '/app/home': RouteRecordInfo<'/app/home', '/app/home', Record<never, never>, Record<never, never>>,
    '/app/library/albums': RouteRecordInfo<'/app/library/albums', '/app/library/albums', Record<never, never>, Record<never, never>>,
    '/app/library/artists': RouteRecordInfo<'/app/library/artists', '/app/library/artists', Record<never, never>, Record<never, never>>,
    '/app/library/recently-added': RouteRecordInfo<'/app/library/recently-added', '/app/library/recently-added', Record<never, never>, Record<never, never>>,
    '/app/library/songs': RouteRecordInfo<'/app/library/songs', '/app/library/songs', Record<never, never>, Record<never, never>>,
    '/app/playlist/all': RouteRecordInfo<'/app/playlist/all', '/app/playlist/all', Record<never, never>, Record<never, never>>,
    '/app/playlist/favorite': RouteRecordInfo<'/app/playlist/favorite', '/app/playlist/favorite', Record<never, never>, Record<never, never>>,
    '/player': RouteRecordInfo<'/player', '/player', Record<never, never>, Record<never, never>>,
    '/sign-in': RouteRecordInfo<'/sign-in', '/sign-in', Record<never, never>, Record<never, never>>,
  }
}
